# Generated by Django 5.0.6 on 2025-04-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DP', '0001_initial'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('dp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_orders', to='DP.dpdata')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Order.order')),
            ],
        ),
    ]
