# Generated by Django 5.0.6 on 2025-04-11 14:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DPData',
            fields=[
                ('DP_id', models.AutoField(primary_key=True, serialize=False)),
                ('Dname', models.CharField(default='', max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('Demail', models.EmailField(default='', max_length=250, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('Dnumber', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number.', regex='^(\\+\\d{1,3}[- ]?)?\\d{10}$')])),
                ('Daddress', models.CharField(default='', max_length=500)),
                ('Dpassword', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Delivery Partner',
                'verbose_name_plural': 'Delivery Partners',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DP.dpdata')),
            ],
        ),
    ]
