# Generated by Django 5.0.6 on 2025-04-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Bride', 'Bride'), ('Groom', 'Groom')], max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='rCategory',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rmain_category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Bride', 'Bride'), ('Groom', 'Groom')], max_length=50)),
                ('rsub_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_type', models.CharField(default='own_product', max_length=255)),
                ('name', models.CharField(default='Unnamed Product', max_length=255)),
                ('description', models.TextField(default='No description available.')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rental_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('brand', models.CharField(blank=True, default='No Brand', max_length=100, null=True)),
                ('color', models.CharField(default='Not Specified', max_length=50)),
                ('image_front', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image_side', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image_back', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('category_specific_id', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('discount_percentage', models.PositiveIntegerField(blank=True, default=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyback', models.BooleanField(default=False)),
                ('test_quantity', models.TextField(default='No test quantity available.')),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ProductS.category')),
                ('seller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Seller.sellerdata')),
            ],
        ),
        migrations.CreateModel(
            name='Resell_Product',
            fields=[
                ('prod_type', models.CharField(default='resell_product', max_length=255)),
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=255)),
                ('rdescription', models.TextField()),
                ('oprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rbrand', models.CharField(blank=True, max_length=100, null=True)),
                ('rcolor', models.CharField(max_length=50)),
                ('rimage_front', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('rimage_side', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('rimage_back', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('rdiscount_percentage', models.PositiveIntegerField(default=30)),
                ('rcategory_specific_id', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resell_products', to='ProductS.rcategory')),
                ('rseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resell_products', to='Seller.sellerdata')),
            ],
        ),
        migrations.CreateModel(
            name='rSizeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsize', models.CharField(max_length=20)),
                ('rquantity', models.PositiveIntegerField(default=1)),
                ('Resell_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_quantities', to='ProductS.resell_product')),
            ],
        ),
        migrations.CreateModel(
            name='SizeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_quantities', to='ProductS.product')),
            ],
        ),
    ]
