"""
Django settings for StyleSurfer project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

 
from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qi0u(t72&go*lr=#=ugol7f@!ye(o1+24e4(sz%gj0gp8r^t&@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['192.168.147.1', 'localhost', '127.0.0.1']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'Customer',
    'Customer.Account',
    'Customer.Buy_Back',
    'Seller',
    'DP',
    'Seller.ProductS',
    'Seller.OrderS',
    'Customer.Product',
    'Customer.Reselling',
    'Customer.Cart',
    'Customer.SpinToWin',
    'Customer.SellWithUs',
    'Customer.Order',
    'DP.OrderD',
    'Seller.BuyBackS',
    'Seller.Offers',
]

SITE_ID = 1


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'StyleSurfer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Customer/templates'),
                 os.path.join(BASE_DIR, 'Seller/templates'),
                 os.path.join(BASE_DIR, 'DP/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Customer.context_processors.session_user_id',
                'Customer.views.cart_item_count',

            ],
        },
    },
]

WSGI_APPLICATION = 'StyleSurfer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')


STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'Customer/static') , 
    os.path.join(BASE_DIR, 'Seller/static') , 
    os.path.join(BASE_DIR, 'Customer/Account/static'),
    os.path.join(BASE_DIR, 'DP/static'), 
    os.path.join(BASE_DIR, 'Seller/ProductS/static'),
    os.path.join(BASE_DIR, 'Seller/OrderS/static'),
    os.path.join(BASE_DIR, 'Seller/BuyBackS/static'),
    os.path.join(BASE_DIR, 'Customer/Product/static'),
    os.path.join(BASE_DIR, 'Customer/Reselling/static'),
    os.path.join(BASE_DIR, 'Customer/Cart/static'),
    os.path.join(BASE_DIR, 'Customer/SellWithUs/static'),
    os.path.join(BASE_DIR, 'Customer/Order/static'),
    os.path.join(BASE_DIR, 'Customer/Buy_Back/static'),
    os.path.join(BASE_DIR, 'DP/OrderD/static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'stylesurfer3@gmail.com'  
EMAIL_HOST_PASSWORD = 'nskg qzdz lohn opbt'  
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Use database-backed sessions
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Session expires when the browser is closed
SESSION_COOKIE_NAME = 'stylesurfer_session'  # Unique session cookie name




# Stripe API Keys (Test Mode)
STRIPE_PUBLIC_KEY = "pk_test_51Qoh0EBIHu6rEvsBSI9L8pWjLdwefVGPfwyUVvZlmYE7InFOQgSmX5YsurY6xGcgChDdqMoRySjzf4mzTG9IbORP00STugEdCO"
STRIPE_SECRET_KEY = "sk_test_51Qoh0EBIHu6rEvsBvFqvIwVo2jSKyYw48sr4GbeWVql52eFywbBiG8JVlv6ytxTpyEIl9RInfWLQlitZM2sX5H0300P58uN8vY"

# Currency
STRIPE_CURRENCY = "inr"

# Payment Methods Supported in India
STRIPE_PAYMENT_METHODS = ["card"]  # ✅ Supports UPI, Net Banking, and Card

ALLOWED_HOSTS = ["*"]

# settings.py
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "10.93.186.241",   # add your USB tether IP
]
