# Generated by Django 5.0.7 on 2025-04-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy_Back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customedesign',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customedesign',
            name='how_many_days',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
