# Generated by Django 5.0.7 on 2025-04-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy_Back', '0002_customedesign_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrequest',
            name='customization_done',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Complete', 'Complete')], default='Pending', max_length=20),
        ),
    ]
