# Generated by Django 5.0.6 on 2025-04-11 14:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductS', '0001_initial'),
        ('SellWithUs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
                ('otp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(default='', max_length=30, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('number', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number.', regex='^(\\+\\d{1,3}[- ]?)?\\d{10}$')])),
                ('password', models.CharField(default='', max_length=128, validators=[django.core.validators.RegexValidator(message='Password must be at least 8 characters long, contain at least one uppercase letter, and one special character', regex='^(?=.[A-Z])(?=.[!@#$%^&()_+{}\\[\\]:;\\"\\\'<>,.?~-])[A-Za-z\\d!@#$%^&()_+{}\\[\\]:;\\"\\\'<>,.?~-]{8,}$')])),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.register')),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.register')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10)),
                ('prod_id', models.PositiveIntegerField(default=0)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductS.product')),
                ('resell_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductS.resell_product')),
                ('sell_with_us', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SellWithUs.customersellerproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.register')),
            ],
        ),
    ]
