# Generated by Django 5.0.6 on 2025-04-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_security', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='Account.register')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('product_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('rid', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('buyback_id', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('name', models.CharField(default='Unnamed Product', max_length=255)),
                ('brand', models.CharField(default='Unnamed Brand', max_length=255)),
                ('image', models.URLField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('stoke', models.CharField(blank=True, max_length=20, null=True)),
                ('days', models.PositiveIntegerField(default=1)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('rental_date', models.TextField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('security', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('prod_type', models.CharField(blank=True, max_length=255, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Cart.cart')),
            ],
        ),
    ]
