# Generated by Django 5.0.6 on 2025-04-11 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyback_id', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyback_status', models.CharField(choices=[('Buy', 'Buy'), ('Back', 'Back'), ('purchased make own product', 'purchased make own product'), ('Pending', 'Pending')], default='Pending', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.register')),
            ],
        ),
        migrations.CreateModel(
            name='Customedesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Product', max_length=255)),
                ('brand', models.CharField(default='Unnamed Brand', max_length=255)),
                ('prod_type', models.CharField(default='Buy_back', max_length=255)),
                ('fimage', models.URLField(blank=True, null=True)),
                ('simage', models.URLField(blank=True, null=True)),
                ('bimage', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('security', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('Customer_status', models.CharField(choices=[('Buy Request', 'Buy Request'), ('Back Request', 'Back Request'), ('pending Request', 'pending Request'), ('Purchase Request', 'Purchase Request')], default='Pending Request', max_length=20)),
                ('days', models.PositiveIntegerField(default=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('rental_date', models.TextField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('gender', models.CharField(max_length=20)),
                ('clothing', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(default='size', max_length=20)),
                ('embroidery_style', models.CharField(default='Standard', max_length=100)),
                ('stone_size', models.CharField(default='Medium', max_length=50)),
                ('placement', models.CharField(default='Front', max_length=100)),
                ('density', models.CharField(default='none', max_length=50)),
                ('thread_option', models.CharField(default='none', max_length=100)),
                ('mirror_shape', models.CharField(default='none', max_length=100)),
                ('mirror_size', models.CharField(default='none', max_length=100)),
                ('border_color', models.CharField(default='none', max_length=100)),
                ('design_style', models.CharField(default='none', max_length=100)),
                ('addons', models.CharField(default='None', max_length=100)),
                ('uploaded_file', models.FileField(upload_to='design_uploads/')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customize_total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customize_seller_description', models.TextField(blank=True, null=True)),
                ('buyback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Buy_Back.buyback')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.sellerdata')),
            ],
        ),
        migrations.CreateModel(
            name='SellerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('buyback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buy_Back.buyback')),
                ('custom_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buy_Back.customedesign')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.sellerdata')),
            ],
        ),
    ]
