# Generated by Django 5.0.6 on 2025-04-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='name', max_length=50)),
                ('last_name', models.CharField(default='name', max_length=50)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('phone', models.CharField(default='0000000000', max_length=15)),
                ('address1', models.TextField(default='')),
                ('address2', models.TextField(default='')),
                ('city', models.CharField(default='Rajkot', max_length=50)),
                ('state', models.CharField(default='Gujarat', max_length=50)),
                ('country', models.CharField(default='India', max_length=50)),
                ('zip_code', models.CharField(default='000000', max_length=10)),
                ('is_accepted', models.BooleanField(default=False)),
                ('order_id', models.CharField(max_length=10, unique=True)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_security', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash_on_delivery', 'Online')], max_length=20, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('security_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Refunded', 'Refunded')], default='Pending', max_length=20)),
                ('is_permanent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Account.register')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('rid', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(default='Unknown', max_length=255)),
                ('brand', models.CharField(default='Generic', max_length=255)),
                ('image', models.URLField(blank=True, default='', null=True)),
                ('color', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('size', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('days', models.PositiveIntegerField(default=1)),
                ('product_order_status', models.CharField(choices=[('Pending', 'Pending'), ('delivered', 'delivered'), ('Completed', 'Completed'), ('Returned', 'Returned')], default='Pending', max_length=20)),
                ('product_payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('product_security_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('rental_date', models.TextField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('security', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('prod_type', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Order.order')),
            ],
        ),
    ]
