# Generated by Django 5.0.6 on 2025-04-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_type', models.CharField(default='sell_with_us', max_length=255)),
                ('csname', models.CharField(default='abc', max_length=255)),
                ('email', models.EmailField(default='stylesurfer3@gmail.com', max_length=254)),
                ('number', models.CharField(default='1234567890', max_length=15)),
                ('addr', models.TextField(default='by default')),
                ('pincode', models.CharField(default='123456', max_length=10)),
                ('boutique', models.CharField(default='StyleSurfer', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('image_front', models.ImageField(upload_to='seller_reviews/')),
                ('image_back', models.ImageField(upload_to='seller_reviews/')),
                ('image_side', models.ImageField(upload_to='seller_reviews/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSellerReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=15)),
                ('addr', models.TextField()),
                ('boutique', models.CharField(default='StyleSurfer', max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('image_front', models.ImageField(upload_to='seller_requests/')),
                ('image_back', models.ImageField(upload_to='seller_requests/')),
                ('image_side', models.ImageField(upload_to='seller_requests/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Verified', 'Verified')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customerproduct_SizeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerSellerProduct_size_quantities', to='SellWithUs.customersellerproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Customersell_SizeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerSellerReq_size_quantities', to='SellWithUs.customersellerreq')),
            ],
        ),
    ]
